{
 "title": "muta-sync",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gap",
    "query": "10s,30s,1m,5m,10m,30m,1h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "height", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "local_height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "muta_sync_local_height{height_type=\"exec_height\"}"
    }
   ]
  },
  {
   "title": "remote_height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "muta_sync_remote_height{height_type=\"exec_height\"}"
    }
   ]
  },
  {
   "title": "fetched_transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "muta_sync_fetch_count{type=\"transaction\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "time_cost_fetch_transaction_each_block",
   "type": "graph",
   "description": "time spent on fetching each block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(muta_sync_fetch_seconds[$gap])\n / \nignoring (height_type) increase(muta_sync_local_height{height_type=\"exec_height\"}[$gap])",
     "legendFormat": "time_usage(s)"
    }
   ]
  }
 ]
}